Add super admin settings
iqb-berlin/testcenter-frontend pull request #297
Opened 2021-06-02 07:36 UTC by mechtelm

Neuer Tab im Superadmin-Bereich zur Änderung von custom texts und appConfig

2021-06-08 17:45 UTC, paflov requested changes

2021-06-08 17:45 UTC, paflov commented on src/app/config/app.config.ts
> +  intro_html = 'Einführungstext nicht definiert';
Wenn es schon ein Interface AppSettings heißt, warum tauchen die einzelnen Felder davon hier wieder auf? Wäre es nicht besser nur ein Feld zu haben `settings: AppSettings`?
Dann wäre auch die getAppConfig-Funktion schlichter und die Gefahr geringer wenn man ein Feld zum Interface hinzufügt es dort zu vergessen. Außerdem hat Klasse dadurch plötzlich Properties mit underscore-Schriebweise, dabei sollte es doch camelCase sein.

2021-06-08 17:45 UTC, paflov commented on src/app/superadmin/settings/app-config.component.ts
> +  expiredHours = {
Das dürfte eine Konstante sein. Außer wäre es vllt. schöner, das mit einer Funktion zu füllen.

2021-06-08 17:45 UTC, paflov commented on src/app/superadmin/settings/app-config.component.ts
> +      const allowedTypes = ['image/png', 'image/jpeg'];
Warum nicht GIF, WebP, SVG?


(https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types)

2021-06-08 17:45 UTC, paflov commented on src/app/config/app.config.ts
> +  impressum_html: string,
Müsste wohl engl. `imprint` oder `legalNotice` heißen.

2021-06-08 17:45 UTC, paflov commented on src/app/config/app.config.ts
> +  getAppConfig(): AppSettings {
Wozu dieser getter, wenn die eh alle public sind?

2021-06-08 17:45 UTC, paflov commented on src/app/config/app.config.ts
> +      this.impressum_html = 'Impressum/Datenschutz nicht definiert';
Ah, das heißt wir müssen beim Update darauf achten, das Impressum wieder herzustellen!

2021-06-08 18:02 UTC, paflov commented on src/app/superadmin/settings/app-config.component.ts
> +      const maxSize = 20971520;
Von Version 1.4 sind es 16mb. Bei 1.3 noch 64 Kb.

2021-06-09 07:04 UTC, mechtelm commented on src/app/config/app.config.ts
> +  intro_html = 'Einführungstext nicht definiert';
Hm es ist auch ungünstig, zwischen SysConfig, AppSettings und AppConfig zu unterscheiden - was ist der erwartete Unterschied? Hintergrund ist, dass ich verschleiern möchte, wo die einzelnen Einstellungen herkommen: Mal aus der Meta-Tabelle, mal abgeleitet aus anderen Quellen.

Das Objekt AppConfig soll überall wahrgenommen und verwendet werden, Die Interfaces SysConfig und AppSettings dienen nur der Kommunikation mit dem Backend und sind veränderbar. AppConfig hingegen soll stabil bleiben. Im constructor der AppConfig werden außerdem die verschiedenen Quellen abgewogen und geprüft. Z. B. kann die Quelle des app_title im Moment ein CustomText sein, aber auch ein AppSetting.

Also ja, es gibt in dieser app.config.ts etwas Aufwand im Verstehen, aber für den Rest der Anwendung ist das eher nützlich, dass es nicht noch ein (dann nicht verstehbares) Unterobjekt settings gibt. Es ist ja für die Anwendung egal, wo der Anwendungstitel herkommt.

2021-06-09 07:08 UTC, mechtelm commented on src/app/superadmin/settings/app-config.component.ts
> +  expiredHours = {
Wenn ein Superadmin Warning-Einstellungen ändert, will er das Ergebnis meist sofort überprüfen, was bei einer Konstante erst nach dem Neuladen ginge. So ist es gleich sichtbar.

Funktion würde ich dann nehmen, wenn sich die zugrundeliegenden Werte an verschiedenen Stellen ändern könnten. Das ist aber nicht der Fall. Nach dem Laden kann sich dieser Wert nur im Superadmin-Bereich ändern.

2021-06-09 07:09 UTC, mechtelm commented on src/app/superadmin/settings/app-config.component.ts
> +      const allowedTypes = ['image/png', 'image/jpeg'];
Ja ok wollte ich nicht alles prüfen.

2021-06-09 07:13 UTC, mechtelm commented on src/app/config/app.config.ts
> +  impressum_html: string,
Ja meinetwegen, wäre eine größere Umbenenn-Aktion. Dann sollte man aber auch die zugehörige Componente (im Moment `PrivacyComponent`) umbenennen. Und eigentlich müsste da auch noch eine Erklärung zur Barrierefreiheit (accessibility) rein. Also dann about_imprint_accessibility_privacy?

2021-06-09 07:17 UTC, paflov commented on src/app/config/app.config.ts
> +  impressum_html: string,
Also legalNotice würde auf jeden Fall accessibility, privacy und imprint mit  einschließen würde ich sagen.

2021-06-09 07:18 UTC, mechtelm commented on src/app/config/app.config.ts
> +  getAppConfig(): AppSettings {
Das bildet zusammen mit `setAppConfig(appConfig: AppSettings): void` (Zeile 111) die Schnittstelle zum Backend und kann hier (so sich das Backend hier mal ändert) angepasst werden. Es geht also um alle Einstellungen, die im Superadmin-Bereich geändert und zurück in die Datenbank gepeichert werden können.

2021-06-09 07:22 UTC, mechtelm commented on src/app/config/app.config.ts
> +      this.impressum_html = 'Impressum/Datenschutz nicht definiert';
An dieser Stelle sind erst die CustomTexts (wenn gesetzt) berücksichtigt, noch nicht die AppSettings aus der Datenbank. Das kommt weiter unten. Und die Datenbank-Einträge (CustomTexts und AppSettings) bleiben beim Update erhalten.

2021-06-09 07:23 UTC, mechtelm commented on src/app/superadmin/settings/app-config.component.ts
> +      const maxSize = 20971520;
Mir egal.

2021-06-09 07:33 UTC, mechtelm commented on src/app/config/app.config.ts
> +  impressum_html: string,
Entschieden: `legalNotice`

2021-06-10 06:15 UTC, merged